### ISSUE TITLE
#0000の文字色のロゴを作成

### ISSUE THREAD

**Issue by naogify** [geolonia/logo#2]
CMYK印刷の時に文字色が薄くなる。![image](https://user-images.githubusercontent.com/8760841/126051964-10d20af7-1793-4047-a1a2-bc20f23d83c2.jpeg)

**Comment by kamataryo** [comment]
これはどうでしょう？
https://github.com/geolonia/logo/blob/master/geolonia-logo_b2.jpg

![https://github.com/geolonia/logo/blob/master/geolonia-logo_b2.jpg](https://github.com/geolonia/logo/raw/master/geolonia-logo_b2.jpg)

**Comment by naogify** [comment]
@kamataryo 
これがあれば大丈夫そうですね。issue 閉じます!
